# Generated by Django 3.1.2 on 2020-11-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201108_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
