# Generated by Django 3.1.2 on 2020-11-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardscollection',
            old_name='advancement_level',
            new_name='rating',
        ),
    ]
