# Generated by Django 3.1.2 on 2020-11-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_flashcards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
