# Generated by Django 3.1.2 on 2020-11-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_flashcards', '0002_auto_20201121_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardscollection',
            name='rating',
        ),
    ]
