# Generated by Django 3.1.2 on 2020-11-16 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_flashcards', '0003_auto_20201116_0157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashcardscollection',
            unique_together={('title', 'owner')},
        ),
    ]
