# Generated by Django 3.1.2 on 2020-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_flashcards', '0004_auto_20201116_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardscollection',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
